//! Shell integration adapters.
//!
//! The application invokes these adapters only to generate shell source. Core
//! commands, configuration, providers, and terminal interaction are shell-neutral.

use clap::ValueEnum;

mod bash;
mod fish;
mod nushell;
mod zsh;

/// A shell integration that can be generated by `shell-ai init`.
#[derive(Clone, ValueEnum)]
pub enum Shell {
    Bash,
    Fish,
    Nu,
    Zsh,
}

pub fn source(shell: Shell, launch_key: &str) -> String {
    match shell {
        Shell::Bash => bash::source(launch_key),
        Shell::Fish => fish::source(launch_key),
        Shell::Nu => nushell::source(launch_key),
        Shell::Zsh => zsh::source(launch_key),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bash_adapter_replaces_the_readline_buffer_after_a_session() {
        let source = source(Shell::Bash, "?");

        assert!(source.contains("command=$(SHELL_AI_SHELL=bash \"$SHELL_AI_BIN\" exec </dev/tty)"));
        assert!(source.contains("READLINE_LINE=$command"));
        assert!(source.contains("READLINE_POINT=${#READLINE_LINE}"));
        assert!(source.contains("bind -x '\"?\":_shell_ai_exec'"));
    }

    #[test]
    fn fish_adapter_replaces_the_commandline_after_a_session() {
        let source = source(Shell::Fish, "?");

        assert!(
            source
                .contains("set -l command (SHELL_AI_SHELL=fish \"$SHELL_AI_BIN\" exec </dev/tty)")
        );
        assert!(source.contains("commandline --replace -- \"$command\""));
        assert!(source.contains("commandline -f repaint"));
        assert!(source.contains("bind \"$_shell_ai_launch_key\" _shell_ai_exec"));
        assert!(source.contains("bind -M insert \"$_shell_ai_launch_key\" _shell_ai_exec"));
    }

    #[test]
    fn nushell_adapter_emits_a_dynamic_keybinding_record() {
        let bindings: serde_json::Value = serde_json::from_str(&source(Shell::Nu, "?")).unwrap();
        let binding = &bindings[0];
        let command = binding["event"]["cmd"].as_str().unwrap();

        assert_eq!(binding["keycode"], "char_?");
        assert_eq!(binding["mode"][0], "emacs");
        assert_eq!(binding["mode"][1], "vi_insert");
        assert!(command.contains("SHELL_AI_SHELL: \"nu\""));
        assert!(command.contains("commandline edit --replace $command"));
        assert!(command.contains("commandline edit --insert \"?\""));
    }

    #[test]
    fn zsh_adapter_redraws_the_original_prompt_after_a_session() {
        let source = source(Shell::Zsh, "?");

        assert!(source.contains("command=$(SHELL_AI_SHELL=zsh \"$SHELL_AI_BIN\" exec </dev/tty)"));
        assert!(source.contains("zle redisplay"));
        assert!(source.contains("LBUFFER=$command"));
        assert!(source.contains("bindkey -M main \"$_shell_ai_launch_key\" _shell_ai_exec"));
    }
}
