baseURL = "https://kenbanks-peng.github.io/shell-ai/"
locale = "en"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableSVG = false
